pipeline {
    agent any

    environment {
        // Path environment variable for docker and minikube CLI
        PATH = "/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:$PATH"
        // Dynamic build version tag based on Jenkins Build Number
        IMAGE_TAG = "v1.0.${BUILD_NUMBER}"
        GIT_REPO_URL = "git@github.com:Sedin-Samson/argocd-dem.git"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Backend Docker Image with tag: backend:${IMAGE_TAG}"
                sh "docker build -t backend:${IMAGE_TAG} ./backend"
            }
        }

        stage('Load Image to Cluster') {
            steps {
                echo "Loading backend:${IMAGE_TAG} into local Minikube cluster..."
                sh """
                    docker save backend:${IMAGE_TAG} | docker exec -i minikube ctr -n k8s.io images import - 2>/dev/null || minikube image load backend:${IMAGE_TAG} 2>/dev/null || echo "Image built in Docker daemon"
                """
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                echo "Updating backend deployment image tag to backend:${IMAGE_TAG}"
                sh """
                    sed -i.bak "s|image: backend:.*|image: backend:${IMAGE_TAG}|g" kubernetes/backend/backend-deployment.yaml
                    rm -f kubernetes/backend/backend-deployment.yaml.bak
                """
            }
        }

        stage('Commit & Push Manifest and Git Release Tag') {
            steps {
                echo "Creating & Pushing Git Release Tag backend-${IMAGE_TAG} to GitHub..."
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh """
                        git config user.name "Jenkins CI"
                        git config user.email "samson@sedintechnologies.com"
                        git add kubernetes/backend/backend-deployment.yaml
                        git commit -m "release: update backend image tag to backend:${IMAGE_TAG} [skip ci]" || echo "No changes to commit"
                        git tag -a "backend-${IMAGE_TAG}" -m "Backend release backend-${IMAGE_TAG} generated by Jenkins" || true
                        git push https://\${GITHUB_TOKEN}@github.com/Sedin-Samson/argocd-dem.git HEAD:main
                        git push https://\${GITHUB_TOKEN}@github.com/Sedin-Samson/argocd-dem.git "backend-${IMAGE_TAG}"
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD Pipeline Completed Successfully! Argo CD will now detect and sync backend:${IMAGE_TAG}."
        }
        failure {
            echo "❌ Pipeline failed! Please check logs."
        }
    }
}
