apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 156916773321.dkr.ecr.ap-south-1.amazonaws.com/argocd-demo-backend:v1.0.15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
