apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sedin-Samson/argocd-dem.git'
    targetRevision: 'frontend-v1.0.0'
    path: 'kubernetes/frontend'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
